// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using XM1.SportsData.Producer.Infrastructure.Configurations;

#nullable disable

namespace XM1.SportsData.Producer.Infrastructure.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20250110054038_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("XM1.SportsData.Producer.Domain.Entities.Fixtures.Partidas", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataInicio")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("GolsTimeCasa")
                        .HasColumnType("int");

                    b.Property<int?>("GolsTimeVisitante")
                        .HasColumnType("int");

                    b.Property<int>("IdApi")
                        .HasColumnType("int");

                    b.Property<bool?>("IsResultadoCompleto")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Rodada")
                        .HasColumnType("int");

                    b.Property<Guid>("TimeCasaId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TimeVisitanteId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("TimeCasaId");

                    b.HasIndex("TimeVisitanteId");

                    b.ToTable("XM1_TB0008_PARTIDAS", (string)null);
                });

            modelBuilder.Entity("XM1.SportsData.Producer.Domain.Entities.Leagues.Liga", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdApi")
                        .HasColumnType("int");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("PaisId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("PaisId");

                    b.ToTable("XM1_TB0006_LIGAS", (string)null);
                });

            modelBuilder.Entity("XM1.SportsData.Producer.Domain.Entities.Leagues.Pais", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdApi")
                        .HasColumnType("int");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("XM1_TB0005_PAISES", (string)null);
                });

            modelBuilder.Entity("XM1.SportsData.Producer.Domain.Entities.Teams.Times", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdApi")
                        .HasColumnType("int");

                    b.Property<Guid>("LigaId")
                        .HasColumnType("char(36)");

                    b.Property<string>("LogoUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("LigaId");

                    b.ToTable("XM1_TB0007_TIMES", (string)null);
                });

            modelBuilder.Entity("XM1.SportsData.Producer.Domain.Entities.Fixtures.Partidas", b =>
                {
                    b.HasOne("XM1.SportsData.Producer.Domain.Entities.Teams.Times", "TimeCasa")
                        .WithMany()
                        .HasForeignKey("TimeCasaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("XM1.SportsData.Producer.Domain.Entities.Teams.Times", "TimeVisitante")
                        .WithMany()
                        .HasForeignKey("TimeVisitanteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TimeCasa");

                    b.Navigation("TimeVisitante");
                });

            modelBuilder.Entity("XM1.SportsData.Producer.Domain.Entities.Leagues.Liga", b =>
                {
                    b.HasOne("XM1.SportsData.Producer.Domain.Entities.Leagues.Pais", "Pais")
                        .WithMany("Ligas")
                        .HasForeignKey("PaisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("XM1.SportsData.Producer.Domain.Entities.Teams.Times", b =>
                {
                    b.HasOne("XM1.SportsData.Producer.Domain.Entities.Leagues.Liga", "Liga")
                        .WithMany()
                        .HasForeignKey("LigaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Liga");
                });

            modelBuilder.Entity("XM1.SportsData.Producer.Domain.Entities.Leagues.Pais", b =>
                {
                    b.Navigation("Ligas");
                });
#pragma warning restore 612, 618
        }
    }
}
